---
apiVersion: v1
kind: Pod
metadata:
  name: csirbd-demo-pod
  namespace: default
spec:
  containers:
   - name: web-server
     image: eu.artifactory.swg-devops.com/sys-ocs-on-z-team-docker-local/nginx:fio
     volumeMounts:
       - name: mypvc
         mountPath: /var/lib/www/html
  volumes:
   - name: mypvc
     persistentVolumeClaim:
       claimName: rbd-pvc
       readOnly: false
