apiVersion: v1
kind: Pod
metadata:
  name: test-raw-block-pod
spec:
  containers:
    - name: my-container
      image: eu.artifactory.swg-devops.com/sys-ocs-on-z-team-docker-local/nginx:fio
      securityContext:
         capabilities: {}
      volumeDevices:
        - devicePath: /dev/rbdblock
          name: my-volume
      imagePullPolicy: IfNotPresent
  volumes:
    - name: my-volume
      persistentVolumeClaim:
        claimName: test-raw-block-pv
